### ISSUE TITLE
你好我这边是网易公司的 你这边看是律师函还是

### ISSUE THREAD

**Issue by Xchkoo** [Ayx03/NeteaseCloudMusic#1]
contact me at kfcvme50@netease.com

**Comment by Ayx03** [comment]
亲爱的 @Xchkoo，

我们注意到您尝试冒充网易公司员工，发送虚假信息。我们严厉警告您停止此类行为，以免触犯法律并造成严重后果。我们强烈建议您立即停止冒充行为，并警惕对他人造成的潜在损害。

谢谢您的理解与合作。
@Ayx03
